# -*- coding: utf-8 -*-
"""把 _scrape/blog/*.json 打包为 src/data/blog.ts"""
import json, os, glob

REPO = r"C:\Users\admin\WorkBuddy\hongye-content-core\2026-05-12-task-1\hymebel-repo"
BLOG = os.path.join(REPO, "_scrape", "blog")
OUT = os.path.join(REPO, "src", "data", "blog.ts")

posts = []
for f in sorted(glob.glob(os.path.join(BLOG, "*.json"))):
    d = json.load(open(f, encoding="utf-8"))
    posts.append(d)
posts.sort(key=lambda p: p.get("date", ""), reverse=True)
print(f"loaded {len(posts)} posts:", [p["id"] for p in posts])

def ts(v) -> str:
    return json.dumps(v, ensure_ascii=False)

lines = ["// AUTO-GENERATED by _scrape/gen_blog_ts.py — 12 posts × kk/uz/en. Do not edit by hand.",
         "import type { Lang } from \"../i18n/ui\";",
         "export type L3 = Record<Lang, string>;",
         "export type BlogTable = { headers: Record<Lang, string[]>; rows: Record<Lang, string[][]> };",
         "export type BlogSection = { h: L3; paras: Record<Lang, string[]> };",
         "export type BlogPost = { id: string; tag: L3; title: L3; excerpt: L3; date: string; readingMin: number; image: string; imageAlt: L3;",
         "  definition: L3; takeaways: Record<Lang, string[]>; sections: BlogSection[]; tables: BlogTable[];",
         "  faqs: { q: L3; a: L3 }[] };",
         "export const posts: BlogPost[] = ["]
for p in posts:
    lines.append("  {")
    lines.append(f"    id: {ts(p['id'])}, tag: {ts(p['tag'])}, title: {ts(p['title'])}, excerpt: {ts(p['excerpt'])},")
    lines.append(f"    date: {ts(p['date'])}, readingMin: {p['readingMin']}, image: {ts(p.get('image',''))}, imageAlt: {ts(p.get('imageAlt',{}))}, definition: {ts(p['definition'])},")
    lines.append(f"    takeaways: {ts(p['takeaways'])},")
    lines.append(f"    sections: {ts(p['sections'])},")
    lines.append(f"    tables: {ts(p.get('tables', []))},")
    lines.append(f"    faqs: {ts(p['faqs'])},")
    lines.append("  },")
lines.append("];")
lines.append("")
lines.append("export function postById(id: string): BlogPost | undefined {")
lines.append("  return posts.find((p) => p.id === id);")
lines.append("}")
lines.append("")
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines))
print("written", OUT)
